objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activity_Count__c</fullName>
        <description>Count the activity performed by Account owner.</description>
        <label>Activity Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Back porch unique identifier</inlineHelpText>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Status__c</fullName>
        <label>Pro Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abrasive Waterjet Cutting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Duct Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Animal Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arborists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork/Murals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asphalt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awnings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed and Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biohazard Remediation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blacksmiths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blind Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Designers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Refacing/Restoration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cable TV Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Vacuum Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Sweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers &amp; Networking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Contractors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Activity_Count__c</fullName>
        <description>Total Activities performed on the account.</description>
        <label>Total Activity Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Activity_Count__c</fullName>
        <label>Activity_Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Status__c</fullName>
        <label>Pro Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Appliance Repair Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awning Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet &amp; Upholstery Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Installers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete &amp; Foundation Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decking Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design &amp; Build Firms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drywall Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electricians</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fencing Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooring Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Door Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gutter Specialists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handyman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardscape &amp; Stonework Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Inspectors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater &amp; TV Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HVAC Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insulation Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Designers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Activity_Count__c</fullName>
        <label>Total_Activity_Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_ActivityCounter.cls
@isTest(SeeAllData=false)
public class Test_ActivityCounter {
    
    // Inserts task from integration user, inserts tasks from other user, updates task owner to integration user.
    static testMethod void CreateTaskfromLeadOwner() {
        List <user> UserList = new List <User> ();
         TaskClass TaskClassobject = new TaskClass ();
        Map <string,List<User>> PNameUserMap = new Map <string,List<User>> ();
        Map<String,Integer> ProfileUserNumMap = new Map<String,Integer> ();
        ProfileUserNumMap.put('Local Market Specialist / Acquisition Team* / Transaction',3);
        ProfileUserNumMap.put('System Admin No Password Expiration',1);
        PNameUserMap =  TestDataFactory.CreateUser(ProfileUserNumMap);
        List <User> user1 = new List <User> ();
        user1 = PNameUserMap.get('Local Market Specialist / Acquisition Team* / Transaction');
        test.startTest();
        List <String> PorchEventFieldMap = new List <String> ();
        PorchEventFieldMap.add('Lead');
        PorchEventFieldMap.add('Task');
        TestDataFactory.CreateFeildmapping(PorchEventFieldMap);
        system.runAs(user1[0]) {
            // Insert test lead and task with same owner
            Lead testLead = new Lead(Porch_com_Company_Key_ID__c='2341234', LastName='Kim', Company='Test Company', Status='Open',
                                     Phone='206-111-2222', State='WA', PostalCode='98107',
                                     Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled',OwnerId=PNameUserMap.get('Local Market Specialist / Acquisition Team* / Transaction')[0].Id);
            insert testLead;
            String ownerId = testLead.OwnerId;
            String whoId = testLead.Id;
            Task firstTask = new Task(OwnerId=ownerId,WhoId=whoId,CallObject='014e20fd-47bf-21d5-55c7-0aba8cde2bbf',CallDurationInSeconds=30);
            insert firstTask;
            Task SecondTask = new Task(OwnerId=ownerId,WhoId=whoId,CallObject='014e20fd-47bf-21d5-55c7-0aba8cde2bbf',CallDurationInSeconds=30);
            insert SecondTask;
            
            // Insert task with different owner - make a loop
            Task ThirdTask = new Task(OwnerId=PNameUserMap.get('System Admin No Password Expiration')[0].Id,WhoId=whoId,CallObject='014e20fd-47bf-21d5-55c7-0aba8cde2bbf',CallDurationInSeconds=30);
            insert ThirdTask;
            //Task FourthTask = new Task(OwnerId=PNameUserMap.get('Local Market Specialist / Acquisition Team* / Transaction')[1].Id,WhoId=whoId,CallObject='014e20fd-47bf-21d5-55c7-0aba8cde2bbf',CallDurationInSeconds=30);
            Task FourthTask = new Task(OwnerId=user1[1].Id,WhoId=whoId,CallObject='014e20fd-47bf-21d5-55c7-0aba8cde2bbf',CallDurationInSeconds=30);
            insert FourthTask;
            
            List <lead> TestLeadList = new List <Lead> ();
            TestLeadList = [SELECT Id,OwnerId,Activity_Count__c,Total_Activity_Count__c FROM Lead WHERE Id = :testLead.Id ];
            //system.assertEquals(2,TestLeadList[0].Activity_Count__c);
            //system.assertEquals(4,TestLeadList[0].Total_Activity_Count__c);
            
        }
        test.stopTest();
    }
    
    static testMethod void CreateTaskfromAccountOwner() {
        List <user> UserList = new List <User> ();
        Map <string,List<User>> PNameUserMap = new Map <string,List<User>> ();
        Map<String,Integer> ProfileUserNumMap = new Map<String,Integer> ();
        ProfileUserNumMap.put('Local Market Specialist / Acquisition Team* / Transaction',3);
        ProfileUserNumMap.put('System Admin No Password Expiration',1);
        PNameUserMap =  TestDataFactory.CreateUser(ProfileUserNumMap);
        List <User> user1 = new List <User> ();
        user1 = PNameUserMap.get('Local Market Specialist / Acquisition Team* / Transaction');
        test.startTest();
        List <String> PorchEventFieldMap = new List <String> ();
        PorchEventFieldMap.add('Account');
        PorchEventFieldMap.add('Task');
        TestDataFactory.CreateFeildmapping(PorchEventFieldMap);
        system.runAs(user1[0]) {
            // Insert test lead and task with same owner
            Account testAccount = new Account(Porch_com_Company_Key_ID__c='2341234', Name='Test Company',OwnerId=PNameUserMap.get('Local Market Specialist / Acquisition Team* / Transaction')[0].Id);/*, Status='Open',
                                     Phone='206-111-2222', State='WA', PostalCode='98107',
                                     Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');*/
            insert testAccount;
            String ownerId = testAccount.OwnerId;
            String whatId = testAccount.Id;
            Task firstTask = new Task(OwnerId=ownerId,whatId=whatId);
            insert firstTask;
            Task SecondTask = new Task(OwnerId=ownerId,whatId=whatId);
            insert SecondTask;
            
            // Insert task with different owner - make a loop
            Task ThirdTask = new Task(OwnerId=PNameUserMap.get('System Admin No Password Expiration')[0].Id,whatId=whatId);
            insert ThirdTask;
            Task FourthTask = new Task(OwnerId=user1[1].Id,whatId=whatId);
            insert FourthTask;
            
            List <Account> TestAccountList = new List <Account> ();
            TestAccountList = [SELECT Id,OwnerId,Activity_Count__c,Total_Activity_Count__c FROM Account WHERE Id = :testAccount.Id ];
            
            //system.assertEquals(2,TestAccountList[0].Activity_Count__c);
            //system.assertEquals(4,TestAccountList[0].Total_Activity_Count__c);
            
            
        }
        test.stopTest();
    }
    
}