objects/Account.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Back porch unique identifier</inlineHelpText>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abrasive Waterjet Cutting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Duct Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Animal Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arborists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork/Murals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asphalt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awnings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed and Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biohazard Remediation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blacksmiths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blind Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Designers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Refacing/Restoration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cable TV Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Vacuum Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Sweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers &amp; Networking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Contractors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <label>Porch.com Company Key ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Appliance Repair Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awning Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet &amp; Upholstery Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Installers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete &amp; Foundation Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decking Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design &amp; Build Firms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drywall Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electricians</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fencing Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooring Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Door Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gutter Specialists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handyman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardscape &amp; Stonework Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Inspectors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater &amp; TV Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HVAC Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insulation Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Designers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Porch_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <description>An Event Porch.com is interested in consuming</description>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <description>Salesforce unique recordidentifier</description>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <description>Salesforce object type</description>
        <label>Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Porch Event</label>
    <nameField>
        <label>Porch Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porch Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Porch_Event_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Event__c</fullName>
        <description>Porch.com Event</description>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fields_Tracked__c</fullName>
        <description>Salesforce fields to track for the Porch.com event.When a value changes for any of these fields, the corresponding record is expected to have met a Porch.com event</description>
        <label>Fields Tracked</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <description>Salesforce object type</description>
        <label>Source Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Porch Event Field Mapping</label>
</CustomObject>

classes/TestLeadAfterUpdate.cls
@isTest 
private class TestLeadAfterUpdate {
   
   static Porch_Event_Field_Mapping__c CreateCustomSetting ( String name, String event , String fieldsTracked , String objName ){
   Porch_Event_Field_Mapping__c cs = new Porch_Event_Field_Mapping__c (
         Name = name,
         Event__c = event,
         Fields_Tracked__c = fieldsTracked,
         Source_Type__c = objName
         );
   insert cs;
   return cs;
 }
 
   /*static Lead CreateNewLead ( String lastname, String company, String phone, String state, String country, String zip ) {
   Lead ld = new Lead (
         LastName = lastname,
         Company = company,
         Status = 'Open',
         phone = phone,
         state = state,
         country = country,
         postalcode=zip,
         county__c = 'tt',
         Pro_type__c = 'test'
         );
   insert ld;
   return ld;
 }*/
   
   private static testmethod void testLead() {
      
       Porch_Event_Field_Mapping__c TestCustomSetting = CreateCustomSetting ('Lead','Test Lead Update' , 'Company,Email' , 'Lead');
       
      Lead TestLead = new Lead( Company = 'Test Company' , LastName = 'Test Lead' , Status = 'Open',
         Porch_com_Company_Key_ID__c = '1234'); 
      insert TestLead;
      
      TestLead.Company = 'TestCompany';
      update TestLead ;
  
      Porch_Event_Field_Mapping__c FieldMapping = Porch_Event_Field_Mapping__c.getInstance('Lead');
      Porch_Event_Field_Mapping__c TestCustomSettingAcc = CreateCustomSetting ('Account','Test Account Update' , 'Name,Type' , 'Account');
    Porch_Event_Field_Mapping__c TestCustomSettingCon = CreateCustomSetting ('Contact' , 'Test Contact Update' , 'Email,FirstName' , 'Contact');
      String Event = FieldMapping.Event__c;
   
      List<Porch_Event__c> PorchEventLeadUpdate = [Select Event__c, Source_Id__c, Source_Type__c, Status__c From Porch_Event__c 
                                                   Where Source_Id__c = :TestLead.Id and Event__c = :Event];
  
      system.assertEquals(PorchEventLeadUpdate.size(), 1);  //Test for Lead Update
      
      NVMConnect__DialList__c DialList = new NVMConnect__DialList__c ( Name = 'Test Dial List' , NVMConnect__Type__c = 'Lead' , NVMConnect__Primary_Phone_Field__c = 'Phone');
      insert DialList;
      
      NVMConnect__Dial_Entry__c DialEntry = new NVMConnect__Dial_Entry__c (NVMConnect__Dial_List__c = DialList.Id , NVMConnect__Primary_Phone__c = 'Phone' , NVMConnect__Order__c = 1 , NVMConnect__URL__c = 'testurl@test.com' , NVMConnect__Focus_Object_Id__c = TestLead.Id);
      insert dialEntry ;
            
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(TestLead.id);

      LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
      lc.setConvertedStatus(convertStatus.MasterLabel);

      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());
      
     }
  }