objects/Account.object
<CustomObject>
    <fields>
        <fullName>Claimed_Date__c</fullName>
        <label>Claimed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Back porch unique identifier</inlineHelpText>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Status__c</fullName>
        <label>Pro Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abrasive Waterjet Cutting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Duct Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Animal Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arborists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork/Murals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asphalt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awnings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed and Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biohazard Remediation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blacksmiths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blind Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Designers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Refacing/Restoration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cable TV Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Vacuum Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Sweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers &amp; Networking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Contractors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Claimed_Date__c</fullName>
        <formula>Account.Claimed_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claimed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <label>Porch.com Company Key ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_User_Key_ID__c</fullName>
        <externalId>true</externalId>
        <label>Porch.com User Key ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Status__c</fullName>
        <label>Pro Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Appliance Repair Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awning Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet &amp; Upholstery Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Installers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete &amp; Foundation Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decking Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design &amp; Build Firms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drywall Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electricians</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fencing Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooring Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Door Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gutter Specialists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handyman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardscape &amp; Stonework Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Inspectors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater &amp; TV Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HVAC Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insulation Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Designers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_PorchLeadConverterResourceV1.cls
@isTest (SeeAllData=true)
private class Test_PorchLeadConverterResourceV1 {

    static void init(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
    }

    static testMethod void testHappyPath(){
        init();
//      Create a lead
        String porchCompanyId = 'testHappyPath';
        String porchUserId = 'testPorchUserId';
        String firstName = 'testFirstName';
        String lastName = 'testLastName';
        String email = 'test@porch.com';
        String mobilePhone = '123-222-3333';
        String accountSource = 'NARI';
        
        Lead testLead = new Lead(Porch_com_Company_Key_ID__c=porchCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert testLead;

        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       firstName, lastName, email, mobilePhone, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('accountId') != null, 'accountId is null');
        System.assert(result.get('contactId') != null, 'contactId is null');
        System.assertEquals(result.get('success'), 'true');

        Contact contact = [SELECT FirstName, LastName, MobilePhone, Email
                           , Porch_com_Company_Key_ID__c, Porch_com_User_Key_ID__c
                           FROM Contact WHERE Id = :result.get('contactId')];

        System.assertEquals(porchCompanyId, contact.Porch_com_Company_Key_ID__c);
        System.assertEquals(porchUserId, contact.Porch_com_User_Key_ID__c);
        System.assertEquals(firstName, contact.FirstName);
        System.assertEquals(lastName, contact.LastName);
        System.assertEquals(mobilePhone, contact.MobilePhone);
        System.assertEquals(email, contact.Email);

        Account account = [SELECT Porch_com_Company_Key_ID__c, Claimed_Date__c, AccountSource FROM Account WHERE Id = :result.get('accountId')];
        System.assert(account.Claimed_Date__c != null, 'claim date is null');
        System.assertEquals(porchCompanyId, account.Porch_com_Company_Key_ID__c);
        System.assertEquals(accountSource, account.AccountSource);
    }

    static testMethod void testAccountAlreadyExists(){
        init();
        String porchCompanyId = 'testAccountAlreadyExists';
        String porchUserId = 'testPorchUserId';
        String firstName = 'testFirstName';
        String lastName = 'testLastName';
        String email = 'test@porch.com';
        String mobilePhone = '123-222-3333';
        String accountSource = 'NARI';

        Account testAccount = new Account(Porch_com_Company_Key_ID__c=porchCompanyId, Name='Test Company');
        insert testAccount;



        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       firstName, lastName, email, mobilePhone, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('message') != null, 'message is null');
        System.assertEquals(result.get('errorCode'), 'SFDC_PORCH_ACCOUNT_ALREADY_EXISTS');
        System.assertEquals(result.get('success'), 'false');
    }

    static testMethod void testDoubleConversion(){
        init();
//      Create a lead
        String porchCompanyId = 'testDoubleConvert';
        String porchUserId = 'testDoubleUserId';
        String firstName = 'testFirstName';
        String lastName = 'testLastName';
        String email = 'test@porch.com';
        String mobilePhone = '123-222-3333';
        String accountSource = 'NARI';
        
        Lead testLead = new Lead(Porch_com_Company_Key_ID__c=porchCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert testLead;

        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       firstName, lastName, email, mobilePhone, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('accountId') != null, 'accountId is null');
        System.assert(result.get('contactId') != null, 'contactId is null');
        System.assertEquals(result.get('success'), 'true');

        //Try and convert again
        result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       firstName, lastName, email, mobilePhone, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('message') != null, 'message is null');
        System.assertEquals(result.get('errorCode'), 'SFDC_PORCH_ACCOUNT_ALREADY_EXISTS');
        System.assertEquals(result.get('success'), 'false');
    }

    static testMethod void testLeadNotFound(){
        init();
        String porchCompanyId = 'testLeadNotFound';
        String porchUserId = 'testPorchUserId';
        String firstName = 'testFirstName';
        String lastName = 'testLastName';
        String email = 'test@porch.com';
        String mobilePhone = '123-222-3333';
        String accountSource = 'NARI';

        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       firstName, lastName, email, mobilePhone, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('message') != null, 'message is null');
        System.assertEquals(result.get('errorCode'), 'SFDC_PORCH_LEAD_NOT_FOUND');
        System.assertEquals(result.get('success'), 'false');
    }

    static testMethod void testNullData(){
        init();
//      Create a lead
        String porchCompanyId = 'testNullData';
        String porchUserId = 'testPorchUserId';
        String accountSource = 'NARI';

        Lead testLead = new Lead(Porch_com_Company_Key_ID__c=porchCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert testLead;

        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       null, null, null, null, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('accountId') != null, 'accountId is null');
        System.assert(result.get('contactId') != null, 'contactId is null');
        System.assertEquals(result.get('success'), 'true');

        Contact contact = [SELECT FirstName, LastName, MobilePhone, Email
                           , Porch_com_Company_Key_ID__c, Porch_com_User_Key_ID__c
                           FROM Contact WHERE Id = :result.get('contactId')];

        System.assertEquals(porchCompanyId, contact.Porch_com_Company_Key_ID__c);
        System.assertEquals(porchUserId, contact.Porch_com_User_Key_ID__c);
        System.assertEquals('Kim', contact.LastName);

        Account account = [SELECT Porch_com_Company_Key_ID__c, Claimed_Date__c, AccountSource FROM Account WHERE Id = :result.get('accountId')];
        System.assert(account.Claimed_Date__c != null, 'claim date is null');
        System.assertEquals(porchCompanyId, account.Porch_com_Company_Key_ID__c);
        System.assertEquals(accountSource, account.AccountSource);
    }

    static testMethod void testBlankData(){
        init();
//      Create a lead
        String porchCompanyId = 'testBlankData';
        String porchUserId = 'testPorchUserId';
        String accountSource = 'NARI';
        
        Lead testLead = new Lead(Porch_com_Company_Key_ID__c=porchCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert testLead;

        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       '', '', '', '', System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('accountId') != null, 'accountId is null');
        System.assert(result.get('contactId') != null, 'contactId is null');
        System.assertEquals(result.get('success'), 'true');

        Contact contact = [SELECT FirstName, LastName, MobilePhone, Email
                           , Porch_com_Company_Key_ID__c, Porch_com_User_Key_ID__c
                           FROM Contact WHERE Id = :result.get('contactId')];

        System.assertEquals(porchCompanyId, contact.Porch_com_Company_Key_ID__c);
        System.assertEquals(porchUserId, contact.Porch_com_User_Key_ID__c);
        System.assertEquals('Kim', contact.LastName);

        Account account = [SELECT Porch_com_Company_Key_ID__c, Claimed_Date__c, AccountSource FROM Account WHERE Id = :result.get('accountId')];
        System.assert(account.Claimed_Date__c != null, 'claim date is null');
        System.assertEquals(porchCompanyId, account.Porch_com_Company_Key_ID__c);
        System.assertEquals(accountSource, account.AccountSource);
    }

    static testMethod void testQueueHandling(){
        init();

        String porchCompanyId = 'testQueueHandling';
        String porchUserId = 'testPorchUserId';
        String firstName = 'testFirstName';
        String lastName = 'testLastName';
        String email = 'test@porch.com';
        String mobilePhone = '123-222-3333';
        String accountSource = 'NARI';
        
        Group queue = [SELECT Id FROM Group WHERE Type = 'Queue' LIMIT 1];

        Lead testLead = new Lead(Porch_com_Company_Key_ID__c=porchCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled', OwnerId=queue.Id);
        insert testLead;

        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       firstName, lastName, email, mobilePhone, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('accountId') != null, 'accountId is null');
        System.assert(result.get('contactId') != null, 'contactId is null');
        System.assertEquals(result.get('success'), 'true');

        Contact contact = [SELECT FirstName, LastName, MobilePhone, Email
                           , Porch_com_Company_Key_ID__c, Porch_com_User_Key_ID__c, OwnerId
                           FROM Contact WHERE Id = :result.get('contactId')];

        System.assertEquals(porchCompanyId, contact.Porch_com_Company_Key_ID__c);
        System.assertEquals(porchUserId, contact.Porch_com_User_Key_ID__c);
        System.assertEquals(firstName, contact.FirstName);
        System.assertEquals(lastName, contact.LastName);
        System.assertEquals(mobilePhone, contact.MobilePhone);
        System.assertEquals(email, contact.Email);
        System.assertEquals(UserInfo.getUserId(), contact.OwnerId);

        Account account = [SELECT Porch_com_Company_Key_ID__c, Claimed_Date__c, OwnerId, AccountSource FROM Account WHERE Id = :result.get('accountId')];
        System.assert(account.Claimed_Date__c != null, 'claim date is null');
        System.assertEquals(porchCompanyId, account.Porch_com_Company_Key_ID__c);
        System.assertEquals(UserInfo.getUserId(), account.OwnerId);
        System.assertEquals(accountSource, account.AccountSource);
    }
    
    static testMethod void testNullAccountSource(){
        init();
//      Create a lead
        String porchCompanyId = 'testHappyPath';
        String porchUserId = 'testPorchUserId';
        String firstName = 'testFirstName';
        String lastName = 'testLastName';
        String email = 'test@porch.com';
        String mobilePhone = '123-222-3333';
        String accountSource = null;
        
        Lead testLead = new Lead(Porch_com_Company_Key_ID__c=porchCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert testLead;

        Map<String, String> result = PorchLeadConverterResourceV1.doPost(porchCompanyId, porchUserId,
                                                                       firstName, lastName, email, mobilePhone, System.now(), accountSource);

        System.assert(result != null, 'response is null');
        System.assert(result.get('accountId') != null, 'accountId is null');
        System.assert(result.get('contactId') != null, 'contactId is null');
        System.assertEquals(result.get('success'), 'true');

        Contact contact = [SELECT FirstName, LastName, MobilePhone, Email
                           , Porch_com_Company_Key_ID__c, Porch_com_User_Key_ID__c
                           FROM Contact WHERE Id = :result.get('contactId')];

        System.assertEquals(porchCompanyId, contact.Porch_com_Company_Key_ID__c);
        System.assertEquals(porchUserId, contact.Porch_com_User_Key_ID__c);
        System.assertEquals(firstName, contact.FirstName);
        System.assertEquals(lastName, contact.LastName);
        System.assertEquals(mobilePhone, contact.MobilePhone);
        System.assertEquals(email, contact.Email);

        Account account = [SELECT Porch_com_Company_Key_ID__c, Claimed_Date__c, AccountSource FROM Account WHERE Id = :result.get('accountId')];
        System.assert(account.Claimed_Date__c != null, 'claim date is null');
        System.assertEquals(porchCompanyId, account.Porch_com_Company_Key_ID__c);
        System.assertEquals(null, account.AccountSource);
    }
}