objects/Account.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Back porch unique identifier</inlineHelpText>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Status__c</fullName>
        <label>Pro Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abrasive Waterjet Cutting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Duct Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Animal Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appliance Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arborists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Artwork/Murals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asphalt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awnings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bed and Breakfast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biohazard Remediation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blacksmiths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blind Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Designers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Refacing/Restoration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cable TV Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Vacuum Cleaning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chimney Sweep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computers &amp; Networking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete Contractors</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <label>Porch.com Company Key ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/County__c.object
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>County</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Porch_com_Company_Key_ID__c</fullName>
        <externalId>true</externalId>
        <label>Porch.com Company Key ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pro_Status__c</fullName>
        <label>Pro Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Pause</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pro_Type__c</fullName>
        <label>Pro Type</label>
        <picklist>
            <picklistValues>
                <fullName>Appliance Repair Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awning Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathtub Refinishing &amp; Liners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabinet Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpenter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet &amp; Upholstery Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carpet Installers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete &amp; Foundation Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decking Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design &amp; Build Firms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drywall Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electricians</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fencing Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flooring Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage Door Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glass Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gutter Specialists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handyman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardscape &amp; Stonework Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Cleaners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Inspectors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater &amp; TV Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HVAC Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insulation Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Designers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_PorchMergeResource.cls
@isTest (SeeAllData=true)
public class Test_PorchMergeResource {    
    static testMethod void testHappyPath_account(){
        String masterCompanyId = 'masterCompanyKey';
        Account masterAccount = new Account(Porch_com_Company_Key_ID__c=masterCompanyId, Name='Master Company');
        insert masterAccount;
        
        String mergeCompanyId = 'mergeCompanyKey';
        Account mergeAccount = new Account(Porch_com_Company_Key_ID__c=mergeCompanyId, Name='Merge Company');
        insert mergeAccount;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PUT';
        req.requestURI = 'https://test.salesforce.com/services/apexrest/merge/' + masterAccount.Id;
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, String> result = PorchMergeResource.doPut(mergeAccount.Id);
        
        System.assert(result != null, 'response is null');
        System.assertEquals(result.get('success'), 'true');
        
        List<Account> masterAccounts = [SELECT Id FROM Account WHERE Id = :masterAccount.Id];
        System.assert(!masterAccounts.isEmpty());
        List<Account> mergedAccounts = [SELECT Id FROM Account WHERE Id = :mergeAccount.Id];
        System.assert(mergedAccounts.isEmpty());
    }    
    
    static testMethod void testHappyPath_contact(){
        Contact masterContact = new Contact(LastName='masterLast');
        insert masterContact;
        
        Contact mergeContact = new Contact(LastName='mergeLast');
        insert mergeContact;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PUT';
        req.requestURI = 'https://test.salesforce.com/services/apexrest/merge/' + masterContact.Id;
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, String> result = PorchMergeResource.doPut(mergeContact.Id);
        
        System.assert(result != null, 'response is null');
        System.assertEquals(result.get('success'), 'true');
        
        List<Contact> masterContacts = [SELECT Id FROM Contact WHERE Id = :masterContact.Id];
        System.assert(!masterContacts.isEmpty());
        List<Contact> mergedContacts = [SELECT Id FROM Contact WHERE Id = :mergeContact.Id];
        System.assert(mergedContacts.isEmpty());
    }
    
    static testMethod void testHappyPath_AccountAndContact(){
        String masterCompanyId = 'masterCompanyKey';
        Account masterAccount = new Account(Porch_com_Company_Key_ID__c=masterCompanyId, Name='Master Company');
        insert masterAccount;
        
        String mergeCompanyId = 'mergeCompanyKey';
        Account mergeAccount = new Account(Porch_com_Company_Key_ID__c=mergeCompanyId, Name='Merge Company');
        insert mergeAccount;
        
        Contact masterContact = new Contact(LastName='masterLast');
        masterContact.AccountId = masterAccount.Id;
        insert masterContact;
        
        Contact mergeContact = new Contact(LastName='mergeLast');
        mergeContact.AccountId = mergeAccount.Id;
        insert mergeContact;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PUT';
        req.requestURI = 'https://test.salesforce.com/services/apexrest/merge/' + masterAccount.Id;
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, String> result = PorchMergeResource.doPut(mergeAccount.Id);
        
        System.assert(result != null, 'response is null');
        System.assertEquals(result.get('success'), 'true');
        
        List<Account> masterAccounts = [SELECT Id FROM Account WHERE Id = :masterAccount.Id];
        System.assert(!masterAccounts.isEmpty());
        List<Account> mergedAccounts = [SELECT Id FROM Account WHERE Id = :mergeAccount.Id];
        System.assert(mergedAccounts.isEmpty());
        
        List<Contact> masterContacts = [SELECT Id FROM Contact WHERE Id = :masterContact.Id];
        System.assert(!masterContacts.isEmpty());
        List<Contact> mergedContacts = [SELECT Id, AccountId FROM Contact WHERE Id = :mergeContact.Id];
        System.assert(!mergedContacts.isEmpty());
        Contact fetchedMergedContact = mergedContacts.get(0);
        System.assertEquals(masterAccount.Id, fetchedMergedContact.AccountId);
    }
    
    static testMethod void testHappyPath_lead(){
        String masterCompanyId = 'masterCompanyKey';
        Lead masterLead = new Lead(Porch_com_Company_Key_ID__c=masterCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert masterLead;
        
        String mergeCompanyId = 'mergeCompanyKey';
        Lead mergeLead = new Lead(Porch_com_Company_Key_ID__c=mergeCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert mergeLead;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PUT';
        req.requestURI = 'https://test.salesforce.com/services/apexrest/merge/' + masterLead.Id;
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, String> result = PorchMergeResource.doPut(mergeLead.Id);
        
        System.assert(result != null, 'response is null');
        System.assertEquals(result.get('success'), 'true');
        
        List<Lead> masterLeads = [SELECT Id FROM Lead WHERE Id = :masterLead.Id];
        System.assert(!masterLeads.isEmpty());
        List<Lead> mergedLeads = [SELECT Id FROM Lead WHERE Id = :mergeLead.Id];
        System.assert(mergedLeads.isEmpty());
    }
    
    static testMethod void testInvalidObject(){
        String masterCompanyId = 'masterCompanyKey';
        Lead masterLead = new Lead(Porch_com_Company_Key_ID__c=masterCompanyId, LastName='Kim', Company='Test Company', Status='Open',
                                 Phone='206-111-2222', State='WA', PostalCode='98107',
                                 Pro_Type__c='Carpenter', County__c='Jones', Pro_Status__c='Enrolled');
        insert masterLead;
        
        String mergeCompanyId = 'mergeCompanyKey';
        Contact mergeContact = new Contact(LastName='Kim');
        insert mergeContact;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PUT';
        req.requestURI = 'https://test.salesforce.com/services/apexrest/merge/' + masterLead.Id;
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, String> result = PorchMergeResource.doPut(mergeContact.Id);
        
        System.assert(result != null, 'response is null');
        System.assertEquals(result.get('success'), 'false');
        System.assert(result.get('message') != null, 'message is null');
        System.assertEquals(result.get('errorCode'), 'SFDC_PORCH_EXCEPTION');
    }    

    static testMethod void testIdDontExist(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'PUT';
        req.requestURI = 'https://test.salesforce.com/services/apexrest/merge/masterNoexist';
        RestContext.request = req;
        RestContext.response = res;
        
        try{
        	PorchMergeResource.doPut('0201010');
        }catch(StringException e){
            return;
        }
        System.assert(false, 'Expected System.StringException');
    }
}