objects/Porch_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <description>An Event Porch.com is interested in consuming</description>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <description>Salesforce unique recordidentifier</description>
        <externalId>true</externalId>
        <label>Source Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <description>Salesforce object type</description>
        <label>Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Porch Event</label>
    <nameField>
        <label>Porch Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porch Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Porch_Event_Field_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Event__c</fullName>
        <description>Porch.com Event</description>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fields_Tracked__c</fullName>
        <description>Salesforce fields to track for the Porch.com event.When a value changes for any of these fields, the corresponding record is expected to have met a Porch.com event</description>
        <label>Fields Tracked</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <description>Salesforce object type</description>
        <label>Source Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Porch Event Field Mapping</label>
</CustomObject>

classes/UpdateObjectsTriggerHandler.cls
/*
  Author : Shirish Goel
  Date : 3/16/2015
  Objective : 
*/
public class UpdateObjectsTriggerHandler {
  
  public void checkFieldsTracked (String objName, Map<Id,SObject> oldmap , Map<Id,SObject> newMap) {
  
     Porch_Event_Field_Mapping__c fieldMapping = new Porch_Event_Field_Mapping__c();
     fieldMapping = Porch_Event_Field_Mapping__c.getInstance(objName);
     String fieldsToCheck = fieldMapping.Fields_Tracked__c ; 
     String event = fieldMapping.Event__c;
     //Splitting the fieldsToCheck String, to check for multiple comma separated values.
     list<String> checkFields = new List<String>();
     checkFields = fieldsToCheck.split(',');
     
     List<Porch_Event__c> toBeInserted = new List<Porch_Event__c>();
     
     
     for (Id i : newMap.keyset()) {
         for (String str : checkFields) {
             if (newMap.get(i).get(str) != oldMap.get(i).get(str)) {
             
                 Porch_Event__c newRecord = new Porch_Event__c();
                 newRecord.Source_Id__c = i ;
                 newRecord.Source_Type__c = objName ;
                 newrecord.Status__c = 'Submitted' ;
                 newRecord.Event__c = event;//'Tracked Field Updated' ;
             
                 toBeInserted.add(newRecord);
     
                 }
             }
         }       
  
     
       try {
          if(toBeInserted.size() != 0){
             insert toBeInserted;                                    //Inserting records in Porch Events object
             }
          }
           catch (DmlException e) {
               System.debug('The following exception has occurred: ' + e.getMessage());
               }         
     
     }

}