objects/Time_Off__c.object
<CustomObject>
    <fields>
        <fullName>Date_Off__c</fullName>
        <label>Date Off</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Off</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Off</label>
    <nameField>
        <displayFormat>TO-{000000}</displayFormat>
        <label>Time Off Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Off</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TimeOffEntryController_test.cls
@isTest
private class TimeOffEntryController_test
{
	@isTest
	static void itShould()
	{
		Map <string,List<User>> PNameUserMap = new Map <string,List<User>> ();
        Map<String,Integer> ProfileUserNumMap = new Map<String,Integer> ();
        ProfileUserNumMap.put('Local Market Specialist / Acquisition Team* / Transaction',3);
        ProfileUserNumMap.put('System Admin No Password Expiration',1);
        PNameUserMap =  TestDataFactory.CreateUser(ProfileUserNumMap);
		Test.setCurrentPage(Page.TimeOffEntry);
		Time_Off__c TO = new Time_Off__c();
		TimeOffEntrycontroller controller = new TimeOffEntrycontroller(new ApexPages.StandardController(TO));
		
		

		TO.employee__c = PNameUserMap.get('Local Market Specialist / Acquisition Team* / Transaction')[0].Id;
		TO.Date_Off__c = System.today();
		controller.TimeOffEntryList.add(TO);
		controller.SaveEntry();
	}

	@isTest
	static void itShouldnt()
	{
		Map <string,List<User>> PNameUserMap = new Map <string,List<User>> ();
        Map<String,Integer> ProfileUserNumMap = new Map<String,Integer> ();
        ProfileUserNumMap.put('Local Market Specialist / Acquisition Team* / Transaction',3);
        ProfileUserNumMap.put('System Admin No Password Expiration',1);
        PNameUserMap =  TestDataFactory.CreateUser(ProfileUserNumMap);
		Test.setCurrentPage(Page.TimeOffEntry);
		Time_Off__c TO = new Time_Off__c();
		TimeOffEntrycontroller controller = new TimeOffEntrycontroller(new ApexPages.StandardController(TO));
		controller.AddFiveEntry();
		controller.SaveEntry();
	}

}